version: "3"

services:
 spa-client:
  container_name: spa_client
  image: spa_client
  build:
   context: ./
   dockerfile: ./src/Clients/angular-spa/Dockerfile

 weather-api:
  container_name: weather-api
  image: weather-api
  build:
   context: ./
   dockerfile: ./src/Resources/weather-api/Dockerfile   
#  identityserver-admin:
#   container_name: identityserver-admin
#   image: identityserver-admin
#   build:
#    context: ./
#    dockerfile: ./src/AuthorizationServer/Dockerfile

