version: "3"

services:
 identityserver-admin: 
  container_name: identityserver-admin
  image: identityserver-admin
  expose: 
    - "80"
  ports: 
    - "5000:80"
  build:
    context: ./
    dockerfile: ./src/AuthorizationServer/Dockerfile

 spa-client:
  container_name: spa_client
  image: spa_client
  build:
   context: ./
   dockerfile: ./src/Clients/angular-spa/Dockerfile

 weather-api:
  container_name: weather-api
  image: weather-api
  build:
   context: ./
   dockerfile: ./src/Resources/weather-api/Dockerfile   

networks:
 default:
  external:
   name: sistemas_reverse-proxy-net
